//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodh.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bodh_DBEntities : DbContext
    {
        public Bodh_DBEntities()
            : base("name=Bodh_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Inquiry> tbl_Inquiry { get; set; }
        public virtual DbSet<Tbl_FileResource> Tbl_FileResource { get; set; }
        public virtual DbSet<tbl_MicroCase> tbl_MicroCase { get; set; }
    }
}
